python train_convnext_SequecingWithzaporednimifrmi.py 
python train_convnext_SequecingWithzaporednimifrmi.py 
python train_convnext_SequecingWithzaporednimifrmi.py 
python train_convnext_SequecingWithzaporednimifrmi.py 
python train_convnext_SequecingWithzaporednimifrmi.py 
python train_convnext_SequecingWithzaporednimifrmi.py 
python train_convnext_SequecingWithzaporednimifrmi.py 
python train_convnext_SequecingWithzaporednimifrmi.py 
python train_convnext_SequecingWithzaporednimifrmi.py 
python train_convnext_SequecingWithzaporednimifrmi.py 
python train_convnext_SequecingWithzaporednimifrmi.py 



