wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.14.1
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681399984.899044
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 5
      - 9
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 23
      4: 3.10.10
      5: 0.14.1
      8:
      - 5
